---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: plantbook-monitor
  labels:
    app.kubernetes.io/version: "v0.0.1"
spec:
  jobLabel: plantbook-monitor
  namespaceSelector:
    matchNames:
    - g1-vladimir
  selector:
    matchLabels:
      app: plantbook
  endpoints:
  - interval: 15s
    port: http
    path: /metrics
