name: Migration

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      arg:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'up [N] Apply all or N up migrations, down [N] Apply all or N down migrations.'
        # Default value if no value is explicitly provided
        default: 'up'
        # Input has to be provided for the workflow to run
        required: true

jobs:

  migration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: migrating using docker
      run: docker run -v $GITHUB_WORKSPACE/database/migrations_schema/:/migrations --network host migrate/migrate -path=/migrations/ -database postgres://${{ secrets.DB }}?sslmode=disable ${{ github.event.inputs.arg }}

