name: integration tests
on:
  push:
    branches-ignore:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      database:
        # Docker Hub image
        image: ghcr.io/proplants/plantbook/database:latest
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "DB_HOST_PORT=database:5432" >> $GITHUB_ENV
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-v1-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-v1-go-
      - name: Test
        run: go test --tags=integration  ./... -race -cover
